# Generated by Django 6.0.4 on 2026-05-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=50, verbose_name='Item ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nama Produk')),
                ('product_url', models.URLField(verbose_name='URL Produk')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('priority', models.CharField(choices=[('high', 'Tinggi'), ('medium', 'Sedang'), ('low', 'Rendah')], default='medium', help_text='Menentukan seberapa sering produk ini dicek harganya', max_length=10, verbose_name='Prioritas')),
                ('is_active', models.BooleanField(default=True, help_text='Nonaktifkan untuk berhenti memantau produk ini', verbose_name='Aktif')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Dicek')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendorstore', verbose_name='Toko Vendor')),
            ],
            options={
                'verbose_name': 'Produk Vendor',
                'verbose_name_plural': 'Produk Vendor',
                'ordering': ['-updated_at'],
                'unique_together': {('store', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(db_index=True, max_length=50, verbose_name='Variant ID')),
                ('name', models.CharField(help_text='Contoh: Merah - XL, Biru - M', max_length=255, verbose_name='Nama Variasi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Harga')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.vendorproduct', verbose_name='Produk Vendor')),
            ],
            options={
                'verbose_name': 'Variasi Produk',
                'verbose_name_plural': 'Variasi Produk',
                'ordering': ['name'],
                'unique_together': {('product', 'variant_id')},
            },
        ),
    ]
