# Generated by Django 6.0.4 on 2026-05-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('PHP', 'Philippine Peso'), ('SGD', 'Singapore Dollar'), ('USD', 'US Dollar')], default='IDR', max_length=3, verbose_name='Mata Uang')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Harga Lama')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Harga Baru')),
                ('price_difference', models.DecimalField(decimal_places=2, help_text='Positif = naik, Negatif = turun', max_digits=14, verbose_name='Selisih Harga')),
                ('old_is_active', models.BooleanField(verbose_name='Status Aktif Lama')),
                ('new_is_active', models.BooleanField(verbose_name='Status Aktif Baru')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Dicatat Pada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.vendorproduct', verbose_name='Produk')),
                ('variant', models.ForeignKey(blank=True, help_text='Kosong jika produk tidak memiliki variasi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productvariant', verbose_name='Variasi')),
            ],
            options={
                'verbose_name': 'Riwayat Harga',
                'verbose_name_plural': 'Riwayat Harga',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
