# Generated by Django 6.0.4 on 2026-05-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='products.vendorproduct', verbose_name='Produk'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Kosong jika produk tidak memiliki variasi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='products.productvariant', verbose_name='Variasi'),
        ),
    ]
