# Generated by Django 6.0.4 on 2026-05-04 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Toko')),
                ('platform', models.CharField(choices=[('shopee', 'Shopee'), ('tokopedia', 'Tokopedia'), ('tiktok', 'TikTok Shop')], db_index=True, default='shopee', max_length=20, verbose_name='Platform')),
                ('shop_id', models.CharField(db_index=True, max_length=50, verbose_name='Shop ID')),
                ('shop_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Toko')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Nonaktifkan untuk berhenti memantau semua produk toko ini', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stores', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik')),
            ],
            options={
                'verbose_name': 'Toko Vendor',
                'verbose_name_plural': 'Toko Vendor',
                'ordering': ['-updated_at'],
                'unique_together': {('platform', 'shop_id')},
            },
        ),
    ]
